name: isar_crdt
description: A new Dart package project.
version: 0.0.2
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  isar: ^3.0.0
  collection: any
  meta: any

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  mockito: ^5.3.2
  build_runner: ^2.3.2
  isar_generator: ^3.0.0
